
#' Construct a scrawl plot from the scrawl object
#'
#' @param data A tibble generated by scrawl_build()
#' @param palette String specifying a scico palette
#'
#' @return A ggplot object
#' @export
scrawl_plot <- function(data, palette = "grayC") {

  picture <- ggplot2::ggplot(
    data = data,        # the data
    mapping = ggplot2::aes(
      x = x,            # plot the x-value
      y = y,            # plot the y-value
      group = path_id,  # each "path_id" is a distinct group
      color = step_id   # paths change color as they step along
    )
  ) +
    ggplot2::geom_path(
      size = .5,     # width of the lines
      alpha = .5,    # transparency of the lines
      show.legend = FALSE
    ) +
    ggplot2::coord_equal() +  # ensure x and y coordinates are on the same scale
    ggplot2::theme_void() +   # use a blank theme
    scico::scale_color_scico(palette = palette) # set the color scheme

  return(picture)
}
